name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # actions/checkout@v4
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Setup Rust
        # dtolnay/rust-toolchain@stable
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8

      - name: Cache cargo
        # Swatinem/rust-cache@v2
        uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae

      - name: Run tests
        run: cargo test
